import React from 'react';
import { Check, X } from 'lucide-react';
import { useLanguage } from '../contexts/LanguageContext';

const ComparisonTable: React.FC = () => {
  const { t } = useLanguage();

  return (
    <section className="py-24 bg-brand-dark relative">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-6">
            {t('comparison.headline')}
          </h2>
          <p className="text-lg text-gray-400 font-medium">
            {t('comparison.subheadline')}
          </p>
        </div>

        <div className="overflow-x-auto pb-8">
          <div className="min-w-[800px] bg-[#121212] rounded-3xl border border-white/10 overflow-hidden shadow-2xl">
            <table className="w-full">
              <thead>
                <tr className="bg-white/5 border-b border-white/5">
                  <th className="px-8 py-8 text-left text-sm font-extrabold text-gray-400 uppercase tracking-wider w-1/4">{t('comparison.feature')}</th>
                  <th className="px-6 py-8 text-center text-sm font-bold text-gray-500 uppercase tracking-wider">{t('comparison.email')}</th>
                  <th className="px-6 py-8 text-center text-sm font-bold text-gray-500 uppercase tracking-wider">{t('comparison.sms')}</th>
                  <th className="px-6 py-8 text-center text-sm font-bold text-gray-500 uppercase tracking-wider">{t('comparison.va')}</th>
                  <th className="px-6 py-8 text-center bg-brand-gold/10 relative border-t-4 border-brand-gold">
                    <span className="text-brand-gold font-extrabold text-lg">{t('comparison.ds')}</span>
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {[
                  { feature: t('comparison.openrate'), email: "20%", sms: "45%", va: t('comparison.na'), ds: t('comparison.whatsapp') },
                  { feature: t('comparison.recoveryrate'), email: "15%", sms: "25%", va: "30%", ds: "37%+", highlight: true },
                  { feature: t('comparison.carts'), email: t('comparison.basiclink'), sms: t('comparison.basiclink'), va: t('comparison.manual'), ds: t('comparison.aiconvo') },
                  { feature: t('comparison.returns'), email: t('comparison.manual'), sms: "No", va: "Yes", ds: t('comparison.aiautomated') },
                  { feature: t('comparison.social'), email: false, sms: false, va: t('comparison.manual'), ds: t('comparison.autogenerated') },
                  { feature: t('comparison.aiimage'), email: false, sms: false, va: false, ds: true },
                  { feature: t('comparison.costmsg'), email: t('comparison.free'), sms: "€0.01", va: t('comparison.na'), ds: "€0" },
                  { feature: t('comparison.24h'), email: true, sms: true, va: false, ds: true },
                  { feature: t('comparison.productresearch'), email: false, sms: false, va: false, ds: true },
                ].map((row, idx) => (
                  <tr key={idx} className={`group hover:bg-white/5 transition-colors ${idx % 2 === 0 ? 'bg-transparent' : 'bg-white/[0.02]'}`}>
                    <td className="px-8 py-6 text-sm font-bold text-gray-200">{row.feature}</td>
                    <td className="px-6 py-6 text-center text-sm text-gray-500 font-medium">
                      {typeof row.email === 'boolean' ? (row.email ? <Check className="mx-auto text-gray-600" size={20} /> : <X className="mx-auto text-red-900/50" size={20} />) : row.email}
                    </td>
                    <td className="px-6 py-6 text-center text-sm text-gray-500 font-medium">
                       {typeof row.sms === 'boolean' ? (row.sms ? <Check className="mx-auto text-gray-600" size={20} /> : <X className="mx-auto text-red-900/50" size={20} />) : row.sms}
                    </td>
                    <td className="px-6 py-6 text-center text-sm text-gray-500 font-medium">
                       {typeof row.va === 'boolean' ? (row.va ? <Check className="mx-auto text-gray-600" size={20} /> : <X className="mx-auto text-red-900/50" size={20} />) : row.va}
                    </td>
                    <td className={`px-6 py-6 text-center font-bold border-l border-r border-brand-gold/10 ${row.highlight ? 'text-brand-gold text-xl bg-brand-gold/5' : 'text-white bg-brand-gold/5'}`}>
                       {typeof row.ds === 'boolean' ? (row.ds ? <div className="bg-brand-gold rounded-full w-8 h-8 flex items-center justify-center mx-auto text-black shadow-[0_0_15px_rgba(245,183,0,0.4)]"><Check strokeWidth={3} size={16} /></div> : <X className="mx-auto text-red-500" size={20} />) : row.ds}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
        
        <div className="mt-8 text-center bg-[#121212] p-6 rounded-2xl border border-brand-purple/30 inline-block mx-auto w-full max-w-3xl">
          <p className="text-gray-300 font-medium text-lg">
            {t('comparison.footer')} <strong className="text-brand-purple">{t('comparison.footer.highlight')}</strong>
          </p>
        </div>
      </div>
    </section>
  );
};

export default ComparisonTable;